### ISSUE TITLE
运行 npm run dev ,执行错误。

### ISSUE THREAD

**Issue by aclk** [daviscai/kone#1]
错误如下所示：
$ npm run dev

> kone@1.0.0 dev /Users/arvin.he/Workspace/git/kone
> nodemon ./index.js

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./index.js`
/Users/arvin.he/Workspace/git/kone/node_modules/memeye/src/index.js:14
module.exports = function ({ port = 23333, log } = {}) {
                           ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/arvin.he/Workspace/git/kone/node_modules/memeye/index.js:1:80)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
[nodemon] app crashed - waiting for file changes before starting...
@daviscai

**Comment by wayso** [comment]
@

**Comment by daviscai** [comment]
你执行了 npm run compile 或者 npm run watch 吗？ 没有的话，要先执行

**Comment by aclk** [comment]
即使使用您提供的命令试了，还是提示同样的错误。@daviscai

**Comment by aclk** [comment]
运行 `npm run compile`

`> kone@1.0.0 compile /Users/arvin.he/Workspace/git/kone`
`> babel --copy-files src/ --out-dir app/`

`src/config/config.js -> app/config/config.js`
`...`
`src/models/cat.js -> app/models/cat.js`
`src/models/user.js -> app/models/user.js`

运行 `npm run dev`

![image](https://user-images.githubusercontent.com/3274901/28812454-646505d2-76c7-11e7-8f06-c8947af93eee.png)

**Comment by aclk** [comment]
@daviscai 是否跟Node.js version有关？我用的是4.4.7。

**Comment by daviscai** [comment]
不支持 node 4, 至少6+,  看 https://travis-ci.org/daviscai/kone 就知道了
